version: "3.8"

services:
  db:
    image: mysql
    restart: unless-stopped
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: nextjs
      MYSQL_DATABASE: kubarocks
    volumes:
      - mysql:/var/lib/mysql

volumes:
  mysql: ~
